### ISSUE TITLE
question

### ISSUE THREAD

**Issue by vahidalvandi** [danielgatis/go-orderbook#1]
Hello
I need an open source maching engine that can process sales orders that are placed in the database through the app, that is, I can finally create something like a binance.
Please advise that this engine of yours can run alongside my app? For example, the membership and wallet sections should be deposited or withdrawn in the my app, and only the trading section should be run in this maching engine?

**Comment by danielgatis** [comment]
Yep, this project is only about the match engine.

**Comment by vahidalvandi** [comment]
Show how it works in a video

**Comment by vahidalvandi** [comment]
Thanks for the tips.
I want to create different wallets and have different networks in my exchange. Please help me in this regard.
